---
title: "R Notebook"
output: html_notebook
---

Install the fitbitr package
```{r}
devtools::install_github("avsecz/fitbitr")
devtools::install_github("r-lib/httr#485")
install.packages("jsonlite")
install.packages("mongolite")
install.packages("lubridate")
install.packages("RCurl")
install.packages("XML")
```


```{r}
library("fitbitr")
library("httr")  
library("jsonlite")
library("mongolite")
library("lubridate")
library("RCurl")
library("XML")
token <- get_fitbit_token()
```

Size of API requests is limited. Call the API for increments by 3 month spans instead.
```{r}
# pull sleep data from January 1-April 11
# req <- fitbit_GET("1/user/4QXD3G/sleep/date/2017-01-01/2017-04-11.json", token = token )
req <-
fitbit_GET("1/user/4QXD3G/activities/steps/date/2016-06-23/2017-11-25.json",
token = token)

output <- toJSON(fitbit_parse(req))

output <- fromJSON(output, simplifyDataFrame = TRUE)
# output <- fromJSON(output)
data <- output$`activities-steps`
data$dateTime <- unlist(data$dateTime)
colnames(data)[2] <- "stepCount"
data$stepCount <- unlist(data$stepCount)
data

# create time series model
# ts <- ts(rev(output$sleep$minutesAsleep), start=c(1, 1), end=c(19, 1), frequency=1)
# plot(ts)
```

```{r}
data$dateTime <- as.Date(data$dateTime, "%Y-%m-%d")
data$stepCount <- as.numeric(data$stepCount)
```

Impute additional date information
```{r}
day <- weekdays(data$dateTime)
week <- week(data$dateTime)
data <- cbind(data, day, week)
data
```

Scrape weather data from https://www.wunderground.com/
```{r}
weather2016 <-
  RCurl::getURL(
  "https://www.wunderground.com/history/airport/KBOS/2016/6/23/CustomHistory.html?dayend=22&monthend=6&yearend=2017&req_city=&req_state=&req_statename=&reqdb.zip=&reqdb.magic=&reqdb.wmo="
  )
  tc <- textConnection(weather2016)
  weather2016 <- readLines(tc)
  close(tc)
  
  pagetree <- htmlTreeParse(weather2016, useInternalNodes = TRUE)
  
  # dates from 6/23/16 - 6/22/17
  weatherDate <-
  unlist(xpathApply(pagetree, "//*[@id='obsTable']/tbody/tr/td[1]/a", xmlValue))
  
  weatherTempHi <-
  unlist(xpathApply(
  pagetree,
  "//*[@id='obsTable']/tbody/tr/td[2]/span",
  xmlValue
  ))
  
  weatherTempLo <-
  unlist(xpathApply(
  pagetree,
  "//*[@id='obsTable']/tbody/tr/td[4]/span",
  xmlValue
  ))
  
  weatherHumidity <-
  unlist(xpathApply(
  pagetree,
  "//*[@id='obsTable']/tbody/tr/td[9]/span",
  xmlValue
  ))
  
  weatherWind <-
  unlist(xpathApply(
  pagetree,
  "//*[@id='obsTable']/tbody/tr/td[18]/span",
  xmlValue
  ))
  
  weatherPrecip <-
  unlist(xpathApply(
  pagetree,
  "//*[@id='obsTable']/tbody/tr/td[20]/span",
  xmlValue
  ))
  
  weatherType <-
  unlist(xpathApply(pagetree, "//*[@id='obsTable']/tbody/tr/td[21]", xmlValue))
  
  # cleaning
  weatherType <-
  weatherType[grepl("\n", weatherType)] # remove empty strings
  weatherType <- gsub("\n", "", weatherType)
  weatherType <- gsub("\t", "", weatherType)
  
  weatherType
  weatherRain <- grepl("Rain", weatherType)
  weatherThunder <- grepl("Thunderstorm", weatherType)
  weatherFog <- grepl("Fog", weatherType)
  weatherSnow <- grepl("Snow", weatherType)

  weatherFrame <-
  as.data.frame(
  cbind(
  weatherDate,
  weatherTempHi,
  weatherTempLo,
  weatherHumidity,
  weatherWind,
  weatherPrecip,
  weatherType,
  weatherRain,
  weatherThunder,
  weatherFog,
  weatherSnow
  )
  )
  
  
  weatherFrame[, 1:6] <- sapply(weatherFrame[, 1:6], as.numeric)
  weatherFrame[, 7] <- sapply(weatherFrame[, 7], as.character)
  weatherFrame[, 8:11] <- sapply(weatherFrame[, 8:11], as.logical)
  
  colnames(weatherFrame) <-
  c("date",
  "tempHi",
  "tempLo",
  "avgHumidity",
  "avgWind",
  "precip",
  "type",
  "rain",
  "thunder",
  "fog",
  "snow")
  weatherFrame
  
  plot(weatherFrame$tempHi)
  
```







